### ISSUE TITLE
create a nav-bar with html and css

### ISSUE THREAD

**Issue by Muhindo-Galien** [Muhindo-Galien/challenge-one-#1]
![Eddy navbar html css](https://user-images.githubusercontent.com/74584848/194780064-e8ca8abe-a4c1-4afe-8cf2-9b1310d9ffbc.JPG)

**Comment by hiteshdate** [comment]
Hello @Muhindo-Galien I want to contribute in your project by creating nav-bar with html & css . I am having good knowledge of html and css for creating better and attractive view of websites.please assign me this issue for make it better .
